### ISSUE TITLE
can't decode utf-8

### ISSUE THREAD

**Issue by higab85** [metakirby5/colorz2#1]
Hey!
I'm using Python 3.5 and I was getting the following error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

with any image I would run through colorz. I tried to fix it myself, and here's the fix: On line 325 of colorz.py:

`  colors = colorz(img_fd, args.num_colors, args.minv, args.maxv, args.bold)`

you're opening the image before opening it:  `img_fd = open(args.image)`
At least in the latest version of Pillow (3.4.2), you only need to hand the location of the image for PIL to be able to open it. So changing that line (line 325 of colorz.py) to the following fixed it for me:

`colors = colorz(args.image, args.num_colors, args.minv, args.maxv, args.bold)`

Just to let you know ;) Awesome project btw, thank you!

**Comment by Naught0** [comment]
Just wanted to say I was having the same problem and this did the trick! Appreciate the post.

**Comment by metakirby5** [comment]
Thanks for the report and investigation! I'll be updating the package shortly - hope I still remember how to do that :)

**Comment by metakirby5** [comment]
Just wanted to mention that your suggested fix breaks generating from URL. However, I found out if a file descriptor is passed in _binary mode_, it works! So, that will be the fix I apply.

**Comment by metakirby5** [comment]
Alright, new version should be up!

**Comment by higab85** [comment]
Awesome Ethan, glad I could help ;)
